version: "3.9"

services:

    stackjs-express:
        build:
            context: .
            dockerfile: etc/docker/stackjs-debug.Dockerfile
            target: prod
        ports:
            - 3000:3000
        restart: always